### ISSUE TITLE
Can use zaringate ?

### ISSUE THREAD

**Issue by Ellip-commerce** [FaridAghili/CI-ZarinPal#2]
can we use `zaringate` by library  ?

**Comment by FaridAghili** [comment]
Use this instead:
https://github.com/MahdiMajidzadeh/CodeIgniter-Zarinpal-gateway

I didn't used/updated CI and ZP for a while.

**Comment by Ellip-commerce** [comment]
but it was `nusoap `and i wanna use `soap`.
I could achieve  by adding `.'/ZarinGate'` to this line : 
`        $this->url = $this->pay_url.$this->authority.'/ZarinGate';`
